version: '2'

services:
    matome:
        container_name: app
        depends_on:
            - db
            - elasticsearch
        build: .
        ports:
            - "80:9000"
        volumes:
            - .:/var/www/html/matome:z
        links:
            - db
        tty: true
    db:
        image: mysql
        user: root
        container_name: db
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        ports:
            - "3306:3306"
        #volumes:
        #    - /data/mysql:/var/lib/mysql
    elasticsearch:
        container_name: elasticsearch
        build:
            context: .
            dockerfile: Dockerfile-elasticsearch
        command: bash -c "elasticsearch && curl -XPUT 'http://localhost:9200/matome' -d '{"index":{"analysis":{"tokenizer":{"kuromoji":{"type":"kuromoji_tokenizer","mode":"search"}},"analyzer":{"default":{"type":"custom","tokenizer":"kuromoji_tokenizer"}}}}}'"
        ports:
            - "9200:9200"