version: '2'

services:
    matome:
        container_name: app
        depends_on:
            - db
        build: .
        ports:
            - "80:9000"
        volumes:
            - .:/var/www/html/matome:z
        links:
            - db
        tty: true
    db:
        image: mysql
        user: root
        container_name: db
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        ports:
            - "3306:3306"
        #volumes:
        #    - /data/mysql:/var/lib/mysql
